# Generated by Django 5.2.1 on 2025-07-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(related_name='libros_en_genero', to='libros.genero'),
        ),
    ]
